# This workflow will build a .NET project

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.100

      - name: Restore dependencies
        run: dotnet restore Booking.Api/Booking.Api.sln

      - name: Build
        run: dotnet build Booking.Api/Booking.Api.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Booking.Api/Booking.Api.sln --no-build --configuration Release --verbosity normal
