
# This workflow will build a .NET project

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore Booking/Booking.sln

      - name: Build
        run: dotnet build Booking/Booking.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test Booking/Booking.sln --no-build --configuration Release --verbosity normal
